language: android
jdk: oraclejdk8
sudo: true

env:
  global:
    - DX_HEAP_SIZE=4096

android:
  components:
     - platform-tools
     - tools
     - build-tools-25.0.2
     - android-25
     - add-on
     - extra

script: sh .travis_script.sh

notifications:
  slack: myexpenses:FExuKgaFD3itm8F65dz2kjyT